language: node_js
dist: trusty
sudo: false
node_js:
  - "node"
  - "lts/*"
  - "9"

addons:
  chrome: stable
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

script:
  - npm test
  - npm run test:firefox
  - npm run test:chrome
  - npm run report-coverage